### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by grodin** [alpmestan/taggy#16]
It would be nice to have `taggy` in Stackage. I know it's not hard to add to `extra-deps` but it would still be nice!

The same applies to `taggy-lens`. Should I open an issue there as well?

**Comment by alpmestan** [comment]
No need to open an issue there. I wouldn't mind having those on stackage. I'll take care of this when I get a chance to, in the upcoming days =)

**Comment by grodin** [comment]
Awesome, thanks!

**Comment by alpmestan** [comment]
PR submitted to Stackage: [here](https://github.com/alpmestan/taggy/issues/16)

Closing the issue. Thanks!
