### ISSUE TITLE
Please release blaze-markup fix on hackage

### ISSUE THREAD

**Issue by jhrcek** [alpmestan/taggy#21]
Hello. Could you please release the following fix on hackage?
https://github.com/alpmestan/taggy/commit/5456c2fa4d377f7802ec5df3d5f50c4ccab2e8ed

Without this, it's not possible to install this library using recent stackage LTS'ses..
I like this library and I'd like to use it in my project ;)

**Comment by alpmestan** [comment]
[Done](https://hackage.haskell.org/package/taggy-0.2.1).

**Comment by jhrcek** [comment]
Great, now I can install it via stack. Thank you!
